config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import common_settings
import core.urls
from user import views
import user.urls
from django.conf.urls.static import static

MEDIA_FILE_PATHS = static(
    common_settings.MEDIA_URL, document_root=common_settings.MEDIA_ROOT
)

urlpatterns = [
    path('admin/',admin.site.urls),
    path('user/', include(user.urls, namespace='user')), 
    path('', include('core.urls', namespace='core')),
    path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),

] + MEDIA_FILE_PATHS

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('movies', views.MovieListView.as_view(), name='MovieList'),
    path('movies/<int:pk>/', views.MovieDetailView.as_view(), name='MovieDetail'),
    path('movie/<int:pk>/', views.MovieDetailView.as_view()),  # <-- Add this line
    #path('404/', views.Custom404View.as_view(), name='Custom404'),
    path('movie/<int:movie_id>/image/upload', views.MovieImageUploadView.as_view(), name='MovieImageUpload'),  # New URL pattern for image upload
    path('movies/top/', views.TopMoviesView.as_view(), name='TopMovies'),  # New URL pattern for top movies
]

core/models.py
from django.db import models
from django.conf import settings
from django.db.models import Sum
from uuid import uuid4
from django.db.models.aggregates import (Sum)

#from core.models import MovieManager
class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'acting_credits__movie'
        )

class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        return qs.select_related('director').prefetch_related('writers', 'actors')
    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))  # <-- Use Sum here
        return qs
    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_score=Sum('vote__value')) # <-- Use Sum here
        qs = qs.exclude(vote_score__isnull=True     ) # Exclude movies with no votes
        qs = qs.order_by('-vote_score')
        qs = qs[:limit]  # Limit the results
        return qs

class Movie (models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED,'NR - Not Rated'),
        (RATED_G,'G - General Audiences'),
        (RATED_PG,'PG - Parental Guidance'),
        (RATED_R,'R - Restricted'),)
    
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField() 
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)

    objects = MovieManager()

    

    class Meta:
        ordering = ['-year', 'title']
    
    

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)

    director = models.ForeignKey(to='Person', 
                                 on_delete=models.SET_NULL, 
                                 null=True,
                                 blank=True,
                                 related_name='directed')
    writers = models.ManyToManyField(to='Person', 
                                     blank=True, 
                                     related_name='writing_credits')
    actors = models.ManyToManyField(to='Person',
                                    through='Role',
                                    blank=True,
                                    related_name='acting_credits')
    
class Role(models.Model):
    movie = models.ForeignKey(to='Movie', on_delete=models.DO_NOTHING)
    person = models.ForeignKey(to='Person', on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(blank=True, null=True)

    objects = PersonManager()

    class Meta:
        ordering = ['last_name', 'first_name']
        

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(self.last_name, self.first_name, self.born.year, self.died.year)
        return '{}, {} ({})'.format(self.last_name, self.first_name, self.born.year)




class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self,movie,user):
        try:
            return Vote.objects.get(
                movie=movie,
                user = user
            )
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user
            )
class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, 'Upvote'),
        (DOWN, 'Downvote'),
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now_add=True)

    objects = VoteManager()
    class Meta:
        unique_together = ('user', 'movie')

def movie_directory_path_with_uuid(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{uuid4().hex}.{ext}"
    return f'uploaded/movies/{instance.movie.id}/{filename}'

class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE, related_name='images')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

core/forms.py
# filepath: /Users/asekibaala/Documents/MyMDB/core/forms.py
from django import forms
from core.models import MovieImage
from django.contrib.auth import get_user_model
from core.models import Vote
from core.models import Movie


class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput(),
        queryset=Movie.objects.all()
        disabled=True
    )
    user = forms.ModelChoiceField(  
        widget=forms.HiddenInput(),
        queryset=get_user_model().objects.all(),
        disabled=True
    )
    class Meta:
        model = MovieImage
        fields = ['movie', 'user', 'image']
        

core/views.py
from django.views.generic import (ListView, DetailView)
from core.models import Movie,Person, Vote,VoteManager
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from .forms import MovieImageForm, VoteForm
from django.views.generic import CreateView, UpdateView 
from django.urls import reverse
from core.mixins import CachePageVaryOnCookiesMixin
import django
from django.core.cache import caches

class MovieDetailView(DetailView):
    #model = Movie
    queryset = Movie.objects.all_with_related_persons_and_score()
    #queryset = Movie.objects.all_with_related_persons()
    #queryset = Movie.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse('core:UpdateVote', kwargs={'movie_id': self.object.id, 'pk': vote.id})
            else:
                vote_form_url = reverse('core:CreateVote',kwargs={'movie_id':self.object.id})
            vote_form = VoteForm(instance=vote)
            context['vote_form'] = vote_form
            context['vote_form_url'] = vote_form_url
        return context

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None
class MovieListView(CachePageVaryOnCookiesMixin, ListView):
    model = Movie
    paginate_by = 10

class PersonDetailView(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()

class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm
    def get_initial(self):
        initial = super().get_initial()
        initial['movie'] = Movie.objects.get(id=self.kwargs['movie_id'])
        initial['user'] = self.request.user
        return initial
    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        return reverse('core:MovieDetail', kwargs={'pk': movie_id})
    
    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk': movie_id})
        return redirect(movie_detail_url)
    
class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset = None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied("You cannot edit someone else's vote.")
        return vote
    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        return reverse('core:MovieDetail', kwargs={'pk': movie_id})
    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk': movie_id})
        return redirect(movie_detail_url)
class MovieImageUploadView(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial['movie'] = Movie.objects.get(id=self.kwargs['movie_id'])
        initial['user'] = self.request.user
        return initial
    def render_to_response(self, context, **response_kwargs):
        movie_id  = self.kwargs['movie_id']
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk': movie_id})
        return movie_detail_url
    
class TopMoviesView(ListView):  
    template_name = 'core/top_movies_list.html'
    queryset = Movie.objects.top_movies(limit=10)

    def get_queryset(self):
        limit = 10
        key = 'top_movies_{}'.format(limit)
        cached_qs = caches['default'].get(key)
        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return cached_qs
        qs = Movie.objects.top_movies(limit=limit)  
        caches['default'].set(key, qs, timeout=300)
        return qs

core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

{% block content %}
<div class="col">
<h1>{{ object.title }}</h1>
<p class="lead">
    {{ object.plot }}
</p>
</div>
<ul class="movie-image list-inline">
    {% for i in object.movieimage_set.all %}
        <li class="list-inline-item">
            <img src="{{ i.image.url }}" alt="{{ object.title }}" class="img-thumbnail">
        </li>
    {% endfor %}
</ul>
<<p>Directed by {{ object.director }}</p>
<p><strong>Year:</strong> {{ object.year }}</p>
<p><strong>Runtime:</strong> {{ object.runtime }} minutes</p>
<p><strong>Website:</strong> <a href="{{ object.website }}">{{ object.website }}</a></p>
{% endblock %}

{% block sidebar %}
<div>
This movie is rated:
   <span class="badge badge-primary">{{ object.get_rating_display }}</span>    
</div>
<div>
    <h2>
    Score: {{ object.score|default_if_none:"TBD" }}
    </h2>
</div>
{% if image_form % }
<div>
    <h3>Upload an image</h3>
    <form method="post" action="{{ image_form_url }}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ image_form.as_p }}
        <button type="submit" class="btn btn-primary">Upload Image</button>
    </form>
</div>
{ % endif %}
<div>
    {% if vote_form %   %}
        <form method="post" action="{{ vote_form_url }}">
            {% csrf_token %}
            {{ vote_form.as_p }}
            <button type="submit" class="btn btn-primary">Submit Vote</button>
        </form>
    {% else %}
        <p><a href="{% url 'login' %}?next={{ request.path }}">Log in</a> to vote for this movie.</p>
    {% endif %}
</div>
{% endblock %}

core/templates/core/movie_list.html
{% extends  'base.html' %}

{% block title %}
All The Movies
{% endblock %}

{% block content %}
<ul>
    {% for movie in object_list %}
        <li>
            <a href="{% url 'core:MovieDetail' pk=movie.id %}">{{ movie }}</a>
        </li>
    {% endfor %}
</ul>
{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}?page=1" class="page-link">&laquo; first</a>
            </li>
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}" class="page-link">previous</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li class="page-item active">
                    <a href="{% url 'core:MovieList' %}?page={{ num }}" class="page-link">{{ num }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a href="{% url 'core:MovieList' %}?page={{ num }}" class="page-link">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}" class="page-link">next</a>
            </li>
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}?page={{ page_obj.paginator.num_pages }}" class="page-link">last &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock %}

core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ object.first_name }} {{ object.last_name }}
{% endblock %}

{% block content %}
  <h1>{{ object }}</h1>
  
  <h2>Actors</h2>
  <ul>
    {% for role in object.role_set.all %}
      <li><a href="{% url 'core:movie_detail' role.movie.id %}">{{ role.movie.title }}
            {{ role.movie }} </a>:
            {{ role.name }}
      </li>
      {% endfor %}
    </ul>
    <h2>Writer</h2>
    <ul>
      {% for movie in object.writing_credits.all %}
        <li><a href="{% url 'core:movie_detail' movie.id %}">{{ movie }}</a></li>
    
      {% endfor %}
    </ul>
    <h2>Director</h2>
    <ul>
      {% for movie in object.directed.all %}
        <li><a href="{% url 'core:movie_detail' movie.id %}">{{ movie }}</a></li>
      
      {% endfor %}
    </ul>
{% endblock %}

core/templates/core/top_movies_list.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}
  Top Movies
{% endblock %}
{% block content %}
  <h1>Top 10 Movies</h1>
  {# {% cache 300 top 10 %} #}  
  <ol>
    {% for movie in object_list %}
      <li>
        <a href="{% url 'core:MovieDetail' movie.id %}">{{ movie }}</a>
      </li>
    {% endfor %}
    </ol>
  {% endcache %}
{% endblock %}