config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import common_settings
import core.urls
from user import views
import user.urls
from django.conf.urls.static import static

MEDIA_FILE_PATHS = static(
    common_settings.MEDIA_URL, document_root=common_settings.MEDIA_ROOT
)

urlpatterns = [
    path('admin/',admin.site.urls),
    path('user/', include(user.urls, namespace='user')), 
    path('', include('core.urls', namespace='core')),
    path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),

] + MEDIA_FILE_PATHS

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('movies', views.MovieListView.as_view(), name='MovieList'),
    path('movies/<int:pk>/', views.MovieDetailView.as_view(), name='MovieDetail'),
    path('movie/<int:pk>/', views.MovieDetailView.as_view()),  # <-- Add this line
    #path('404/', views.Custom404View.as_view(), name='Custom404'),
    path('movie/<int:movie_id>/image/upload', views.MovieImageUploadView.as_view(), name='MovieImageUpload'),  # New URL pattern for image upload
    path('movies/top/', views.TopMoviesView.as_view(), name='TopMovies'),  # New URL pattern for top movies
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0", shrink-to-fit=no>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>{% block title %}MyMDB{% endblock %}</title>
        <style>
            .mymdb-masthead{
                background-color: #EEEEEE;
                margin-bottom: 1em;
            }
        </style>
    </head>
    <body>
    <div class="mymdb-masthead">
        <div class="container">
            <nav class="nav">
                <div class="navbar">MyMDB</div>
                <a class="nav-link" href="{% url 'core:MovieList' %}">Movies</a>
                <a class="nav-link" href="{% url 'core:TopMovies' %}">Top 10 Movies</a>
            </nav>
        </div> 
    </div> 

    <div class="container">
        <div class="row">
            <div class="col-sm-8 mymdb-main">
                {% block content %}
                <!-- Content will be injected here -->
                {% endblock %}
            </div>
            <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
                {% block sidebar %}
                <!-- Sidebar content can go here -->
                {% endblock %}
            </div>
        </div>
    </div>
    </body> 
    </html>